const ADMIN_EMAIL='mfatihdumlu@gmail.com',ADMIN_HASH='c1a9f2b636304ee56a6cd7c4666d5a1f4bb8f93690f001cfdd2118eaa7d963e1',$=s=>document.querySelector(s),D={branch:'Emigro',address:'',reviewUrl:'',title:'Hoe was je ervaring?',text:'Jouw mening helpt ons om elke dag beter te worden.',instagram:[],whatsapp:[]};
function e(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function ok(u){try{let x=new URL(u);return x.protocol==='https:'||x.protocol==='http:'}catch{return false}}
function b64(s){let a=new TextEncoder().encode(s),b='';a.forEach(x=>b+=String.fromCharCode(x));return btoa(b).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';let b=atob(s),a=Uint8Array.from(b,c=>c.charCodeAt(0));return new TextDecoder().decode(a)}
function addItem(type,data={}){let w=document.createElement('div');w.className='repeat '+(type==='ig'?'igItem':'waItem');w.innerHTML=`<div class="repeatTop"><b>${type==='ig'?'Instagram-post':'WhatsApp-groep'}</b><button class="remove">Verwijderen</button></div><label>Titel</label><input class="itemTitle" value="${e(data.title||'')}"><label>Link</label><input class="itemUrl" value="${e(data.url||'')}"><label>Korte tekst</label><input class="itemText" value="${e(data.text||'')}">`;w.querySelector('.remove').onclick=()=>w.remove();$(type==='ig'?'#igAdmin':'#waAdmin').appendChild(w)}
function cfg(){return{branch:$('#branch').value.trim()||'Emigro',address:$('#address').value.trim(),reviewUrl:$('#reviewUrl').value.trim(),title:$('#title').value.trim()||D.title,text:$('#text').value.trim()||D.text,instagram:[...document.querySelectorAll('.igItem')].map(x=>({title:x.querySelector('.itemTitle').value.trim(),url:x.querySelector('.itemUrl').value.trim(),text:x.querySelector('.itemText').value.trim()})).filter(x=>x.url),whatsapp:[...document.querySelectorAll('.waItem')].map(x=>({title:x.querySelector('.itemTitle').value.trim(),url:x.querySelector('.itemUrl').value.trim(),text:x.querySelector('.itemText').value.trim()})).filter(x=>x.url)}}
function fill(c){$('#branch').value=c.branch||'';$('#address').value=c.address||'';$('#reviewUrl').value=c.reviewUrl||'';$('#title').value=c.title||D.title;$('#text').value=c.text||D.text;$('#igAdmin').innerHTML='';(c.instagram||[]).forEach(x=>addItem('ig',x));$('#waAdmin').innerHTML='';(c.whatsapp||[]).forEach(x=>addItem('wa',x))}
function render(c){$('#pubTitle').textContent=c.title||D.title;$('#pubText').textContent=c.text||D.text;$('#pubBranch').textContent=c.branch||'Emigro';$('#pubAddress').textContent=c.address||'';let r=$('#reviewBtn');if(ok(c.reviewUrl)){r.href=c.reviewUrl;r.style.opacity='1';r.style.pointerEvents='auto'}else{r.href='#';r.style.opacity='.5';r.style.pointerEvents='none'}let ig=(c.instagram||[]).filter(x=>ok(x.url));$('#igSection').classList.toggle('hidden',!ig.length);$('#igGrid').innerHTML=ig.map(x=>`<article class="card"><div class="cardIcon">◎</div><h3>${e(x.title||'Instagram')}</h3><p>${e(x.text||'Bekijk onze nieuwste post op Instagram.')}</p><a class="miniBtn" href="${e(x.url)}" target="_blank" rel="noopener">Bekijk op Instagram →</a></article>`).join('');let wa=(c.whatsapp||[]).filter(x=>ok(x.url));$('#waSection').classList.toggle('hidden',!wa.length);$('#waGrid').innerHTML=wa.map(x=>`<article class="card"><div class="cardIcon">◈</div><h3>${e(x.title||'WhatsApp')}</h3><p>${e(x.text||'Word lid en blijf op de hoogte.')}</p><a class="miniBtn" href="${e(x.url)}" target="_blank" rel="noopener">Open WhatsApp →</a></article>`).join('')}
async function hash(s){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function url(c){return location.origin+location.pathname+'?d='+encodeURIComponent(b64(JSON.stringify(c)))}
function pub(){let c=cfg();localStorage.setItem('emigroReviewCfg',JSON.stringify(c));let u=url(c);$('#shareBox').textContent=u;$('#shareBox').dataset.url=u;$('#qrImg').src='https://api.qrserver.com/v1/create-qr-code/?size=360x360&margin=10&data='+encodeURIComponent(u);$('#qrImg').classList.remove('hidden')}
function showAdmin(){ $('#publicApp').classList.add('hidden');let yes=sessionStorage.getItem('reviewAdmin')==='1';$('#loginView').classList.toggle('hidden',yes);$('#adminView').classList.toggle('hidden',!yes);if(yes)fill(JSON.parse(localStorage.getItem('emigroReviewCfg')||'null')||D)}
function showPublic(){ $('#loginView').classList.add('hidden');$('#adminView').classList.add('hidden');$('#publicApp').classList.remove('hidden');let p=new URLSearchParams(location.search),c=D;if(p.get('d'))try{c=JSON.parse(unb64(p.get('d')))}catch{}render(c)}
$('#loginBtn').onclick=async()=>{let h=await hash($('#loginPass').value);if($('#loginEmail').value.trim().toLowerCase()===ADMIN_EMAIL&&h===ADMIN_HASH){sessionStorage.setItem('reviewAdmin','1');showAdmin()}else $('#loginError').classList.remove('hidden')};
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('reviewAdmin');showAdmin()};$('#addIg').onclick=()=>addItem('ig');$('#addWa').onclick=()=>addItem('wa');$('#saveBtn').onclick=()=>{localStorage.setItem('emigroReviewCfg',JSON.stringify(cfg()));$('#savedMsg').textContent='Opgeslagen ✓';setTimeout(()=>$('#savedMsg').textContent='',1600)};$('#publishBtn').onclick=pub;$('#copyBtn').onclick=async()=>{let u=$('#shareBox').dataset.url;if(u){await navigator.clipboard.writeText(u);$('#copyBtn').textContent='Gekopieerd ✓';setTimeout(()=>$('#copyBtn').textContent='Link kopiëren',1400)}};$('#openBtn').onclick=()=>{let u=$('#shareBox').dataset.url;if(u)open(u,'_blank')};new URLSearchParams(location.search).get('admin')==='1'?showAdmin():showPublic();